<a href="https://colab.research.google.com/github/yangpimpollo/temp2/blob/main/stocastic.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

# Definir la matriz de transición
A = np.array([[0.2, 0.8], [0.5, 0.5]])

# Calcular las probabilidades límite
def calcular_probabilidades_limite(A):
    while True:
        A_anterior = A
        A = np.dot(A, A)
        if np.allclose(A, A_anterior):
            break
    return A

In [ ]:
import numpy as np
A = np.array([[0.35, 0.60, 0.05], [0.30, 0.60, 0.10], [0.25, 0.40, 0.35]])

def multiplicar_matrices(A, n):
  for i in range(1, n):
    A = np.dot(A, A)
  return A

#A
probabilidades_limite = multiplicar_matrices(A, 40)
probabilidades_limite[0,:]

array([0.30985662, 0.57746007, 0.11267514])

In [ ]:
import numpy as np

arr = np.array([[0.2, -0.05], [-0.1, 0.2]])
print(arr)

arr_inv = np.linalg.inv(arr)

print(arr_inv)

[[ 0.2  -0.05]
 [-0.1   0.2 ]]
[[5.71428571 1.42857143]
 [2.85714286 5.71428571]]


In [ ]:
5.71428571 + 1.42857143

7.14285714

In [ ]:
arr1 = np.array([[1, 1], [4, 2]])
arr2 = np.array([[2, 3], [-5, 12]])
print(arr1)
print(arr2)
arr3 = arr1 + arr2
print(arr3)

[[1 1]
 [4 2]]
[[ 2  3]
 [-5 12]]
[[ 3  4]
 [-1 14]]


In [ ]:
N1 = np.array([[0, 0.4, 0], [0, 0, 0.3], [0, 0, 0]])
I = np.identity(3)
i2 = np.ones((3, 1))       #np.array([[1], [1], [1]])

R = np.linalg.inv(I - N1)

print(np.dot(R,i2))

[[1.52]
 [1.3 ]
 [1.  ]]


In [ ]:
A = np.array([[0.35, 0.60, 0.05], [0.30, 0.60, 0.10], [0.25, 0.40, 0.35]])

result = np.linalg.matrix_power(A, 40)

result

array([[0.30985915, 0.57746479, 0.11267606],
       [0.30985915, 0.57746479, 0.11267606],
       [0.30985915, 0.57746479, 0.11267606]])

In [ ]:
A = np.array([[0.35, 0.60, 0.05], [0.30, 0.60, 0.10], [0.25, 0.40, 0.35]])

result = A**20

result
#print(result)

array([[7.60958350e-10, 3.65615844e-05, 9.53674316e-27],
       [3.48678440e-11, 3.65615844e-05, 1.00000000e-20],
       [9.09494702e-13, 1.09951163e-08, 7.60958350e-10]])

In [ ]:

A = np.array([[.8, .2, .0], [.3, .5, .2], [.1, .1, .8]])

result = np.linalg.matrix_power(A, 100)

result

array([[0.5 , 0.25, 0.25],
       [0.5 , 0.25, 0.25],
       [0.5 , 0.25, 0.25]])

In [ ]:
import numpy as np

A = np.array([[.7, .1, .1, .1], [.1, .7, .1, .1], [.1, .1, .7, .1], [.1, .1, .1, .7]])

result = np.linalg.matrix_power(A, 100)

print(A)
print(result)

[[0.7 0.1 0.1 0.1]
 [0.1 0.7 0.1 0.1]
 [0.1 0.1 0.7 0.1]
 [0.1 0.1 0.1 0.7]]
[[0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]
 [0.25 0.25 0.25 0.25]]
